//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSam.MainCon
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceJournal
    {
        public int ID { get; set; }
        public Nullable<int> Estimation { get; set; }
        public Nullable<int> IDMaterial { get; set; }
        public Nullable<int> IDStudent { get; set; }
    
        public virtual EdMaterial EdMaterial { get; set; }
        public virtual Student Student { get; set; }
    }
}
